In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import warnings
warnings.filterwarnings('ignore')
plt.style.use('seaborn-v0_8-whitegrid')

In [2]:
time_df = pd.read_csv('/Users/shabadpreetsingh/Downloads/Socbiz Summer Project/UrbanEV_ SZ_districts/time.csv')
print(time_df.shape)
print(time_df.head(5))
#It has 8,640 rows. Each row is one 5-minute slot from June 19 to July 18.
# 8640 = 30 days × 24 hours × 12 (five-minute intervals per hour) = 8640 ✓

(8640, 6)
   month  day  year  hour  minute  second
0      6   19  2022     0       0       0
1      6   19  2022     0       5       0
2      6   19  2022     0      10       0
3      6   19  2022     0      15       0
4      6   19  2022     0      20       0

In [3]:
occ_df = pd.read_csv('/Users/shabadpreetsingh/Downloads/Socbiz Summer Project/UrbanEV_ SZ_districts/occupancy.csv')
print(occ_df.shape)
print(occ_df.head(5))
#102,105,107 wagera sab station ids hai
# Each cell value: how many chargers at that station are occupied right now

(8640, 248)
   timestamp  102  105  107  108  109  110  111  115  123  ...  1160  1162  \
0          1   12   16   24   15    6    8   24    1    2  ...     0    12
1          2   12   16   24   15    6    8   24    1    2  ...     0    12
2          3   12   16   24   15    6    8   24    1    2  ...     0    12
3          4   12   16   24   15    6    8   24    1    2  ...     0    12
4          5   12   16   24   15    6    8   24    1    2  ...     0    12

   1163  1164  1166  1167  1168  1170  1172  1173
0     1    38    26   162    10     1     8    15
1     1    38    26   162    10     1     8    15
2     1    38    26   164    10     1     8    15
3     1    38    26   166    10     1     8    15
4     1    38    26   168    10     1     8    15

[5 rows x 248 columns]

In [4]:
vol_df = pd.read_csv('/Users/shabadpreetsingh/Downloads/Socbiz Summer Project/UrbanEV_ SZ_districts/volume.csv')
print(vol_df.shape)
print(vol_df.head(5))
# same structure — kWh consumed

(8640, 248)
   timestamp       102       105       107    108       109       110  \
0          1  2.858333  5.907222  6.478889  5.145  2.286667  3.048889
1          2  4.375000  9.041667  9.916667  7.875  3.500000  4.666667
2          3  4.375000  9.041667  9.916667  7.875  3.500000  4.666667
3          4  4.375000  9.041667  9.916667  7.875  3.500000  4.666667
4          5  4.375000  9.041667  9.916667  7.875  3.500000  4.666667

        111       115       123  ...  1160      1162      1163       1164  \
0  5.526111  0.381111  0.762222  ...   0.0  2.286667  0.381111  12.195556
1  8.458333  0.583333  1.166667  ...   0.0  3.500000  0.583333  18.666667
2  8.458333  0.583333  1.166667  ...   0.0  3.500000  0.583333  18.666667
3  8.458333  0.583333  1.166667  ...   0.0  3.500000  0.583333  18.666667
4  8.458333  0.583333  1.166667  ...   0.0  3.500000  0.583333  18.666667

        1166        1167      1168      1170      1172      1173
0   8.956111  240.236111  5.335556  0.381111  2.286667  2.096111
1  13.708333  367.708333  8.166667  0.583333  3.500000  3.208333
2  13.708333  367.708333  8.166667  0.583333  3.500000  3.208333
3  13.708333  426.641667  8.166667  0.583333  3.500000  3.208333
4  13.708333  452.708333  8.166667  0.583333  3.500000  3.208333

[5 rows x 248 columns]

In [5]:
price_df = pd.read_csv('/Users/shabadpreetsingh/Downloads/Socbiz Summer Project/UrbanEV_ SZ_districts/price.csv')
print(price_df.shape)
print(price_df.head(5))

(8640, 248)
   timestamp    102       105       107   108    109    110       111   115  \
0          1  0.924  1.124167  0.926364  0.99  1.004  1.015  1.111818  1.15
1          2  0.924  1.124167  0.926364  0.99  1.004  1.015  1.111818  1.15
2          3  0.924  1.124167  0.926364  0.99  1.004  1.015  1.111818  1.15
3          4  0.924  1.124167  0.926364  0.99  1.004  1.015  1.111818  1.15
4          5  0.924  1.124167  0.926364  0.99  1.004  1.015  1.111818  1.15

        123  ...  1160   1162  1163      1164  1166      1167      1168  1170  \
0  0.543333  ...  0.69  0.905   0.7  0.956875  1.04  0.753185  0.906667   1.2
1  0.543333  ...  0.69  0.905   0.7  0.956875  1.04  0.753185  0.906667   1.2
2  0.543333  ...  0.69  0.905   0.7  0.956875  1.04  0.753185  0.906667   1.2
3  0.543333  ...  0.69  0.905   0.7  0.956875  1.04  0.753185  0.906667   1.2
4  0.543333  ...  0.69  0.905   0.7  0.956875  1.04  0.753185  0.906667   1.2

    1172    1173
0  1.038  1.0425
1  1.038  1.0425
2  1.038  1.0425
3  1.038  1.0425
4  1.038  1.0425

[5 rows x 248 columns]

In [6]:
dur_df = pd.read_csv('/Users/shabadpreetsingh/Downloads/Socbiz Summer Project/UrbanEV_ SZ_districts/duration.csv')
print(dur_df.shape)
print(dur_df.head(5))
################################################ session duration wali baat samajh nahi aayi
# same structure — session duration

# Yeh file batati hai ki us specific 5-minute ke window mein, us station par total kitni der ki charging hui (sab gaadiyon ko milakar).
# Iska math samajhiye:
# Agar 1 gaadi pure 5 minute tak charge hoti hai, toh wo system mein 0.0833 hours (5/60) ka duration add karti hai.
# Agar kisi row mein Station '102' ke aage 0.75 likha hai, toh 0.75 hours ka matlab hota hai 45 minutes.
# Ab 45 minutes ko 5 se divide kariye (45/5 = 9). Iska matlab us 5 minute ke interval mein exact 9 gaadiyan ek saath charge ho rahi thi!

# Isko cross-verify karte hain baaki files ke saath:
# Aapke paas jo dusri files hain, unse yeh poori tarah prove ho jata hai:
# information.csv: Station '102' par total 30 chargers (piles) hain.
# occupancy.csv: Same time par Station '102' ki occupancy 12 hai. Yaani 30 mein se 12 chargers par gaadiyan khadi hain.
# duration.csv: Duration 0.75 (yaani 9 gaadiyon ke barabar) hai.
# Result: Iska matlab 12 gaadiyan wahan park hain, jisme se 9 gaadiyan actively charge ho rahi hain, 
# aur 3 gaadiyan aisi hain jo ya toh fully charge ho chuki hain par abhi bhi plug-in hain, ya fir unki charging shuru nahi hui hai.

(8640, 248)
   timestamp   102       105   107       108       109       110   111  \
0          1  0.49  0.871111  0.98  0.762222  0.326667  0.381111  0.98
1          2  0.75  1.333333  1.50  1.166667  0.500000  0.583333  1.50
2          3  0.75  1.333333  1.50  1.166667  0.500000  0.583333  1.50
3          4  0.75  1.333333  1.50  1.166667  0.500000  0.583333  1.50
4          5  0.75  1.333333  1.50  1.166667  0.500000  0.583333  1.50

        115       123  ...  1160      1162      1163      1164      1166  \
0  0.054444  0.108889  ...   0.0  0.326667  0.054444  1.905556  1.306667
1  0.083333  0.166667  ...   0.0  0.500000  0.083333  2.916667  2.000000
2  0.083333  0.166667  ...   0.0  0.500000  0.083333  2.916667  2.000000
3  0.083333  0.166667  ...   0.0  0.500000  0.083333  2.916667  2.000000
4  0.083333  0.166667  ...   0.0  0.500000  0.083333  2.916667  2.000000

        1167      1168      1170      1172      1173
0   8.493333  0.544444  0.054444  0.435556  0.326667
1  13.000000  0.833333  0.083333  0.666667  0.500000
2  13.000000  0.833333  0.083333  0.666667  0.500000
3  13.288889  0.833333  0.083333  0.666667  0.500000
4  13.416667  0.833333  0.083333  0.666667  0.500000

[5 rows x 248 columns]

In [7]:
info_df = pd.read_csv('/Users/shabadpreetsingh/Downloads/Socbiz Summer Project/UrbanEV_ SZ_districts/information.csv')
print(info_df.shape)
print(info_df.head(5))

(247, 10)
   num  grid  count  fast_count  slow_count  area       lon        la  CBD  \
0    1   102     30           3          27  0.71  114.1030  22.54041    0
1    3   105     93           0          93  0.77  114.1208  22.55127    0
2    5   107     88           2          86  0.89  114.1304  22.54486    0
3    6   108     39           0          39  1.26  114.1315  22.55403    0
4    7   109     39           0          39  3.15  114.1430  22.56388    0

   dynamic_pricing
0                0
1                0
2                0
3                0
4                0

In [8]:
stations_df = pd.read_csv('/Users/shabadpreetsingh/Downloads/Socbiz Summer Project/UrbanEV_ SZ_districts/stations.csv')
print(stations_df.shape)
print(stations_df.head(5))

(1706, 6)
   station_id   latitude   longitude  fast  slow  count
0           1  22.716272  113.826349     5     5     10
1           2  22.678851  114.049721    20     0     20
2           3  22.509541  114.058510     0     8      8
3           4  22.605970  114.122110     0     6      6
4           5  22.732771  113.816951     0    55     55

In [9]:
time_df['datetime'] = pd.to_datetime(
    time_df[['year', 'month', 'day', 'hour', 'minute', 'second']]
)

print(f"Date range: {time_df['datetime'].min()}  →  {time_df['datetime'].max()}")
print(f"Total time span: 30 days, sampled every 5 minutes")

Date range: 2022-06-19 00:00:00  →  2022-07-18 23:55:00
Total time span: 30 days, sampled every 5 minutes

In [10]:
print(time_df.head())
print(time_df['datetime'].head())

   month  day  year  hour  minute  second            datetime
0      6   19  2022     0       0       0 2022-06-19 00:00:00
1      6   19  2022     0       5       0 2022-06-19 00:05:00
2      6   19  2022     0      10       0 2022-06-19 00:10:00
3      6   19  2022     0      15       0 2022-06-19 00:15:00
4      6   19  2022     0      20       0 2022-06-19 00:20:00
0   2022-06-19 00:00:00
1   2022-06-19 00:05:00
2   2022-06-19 00:10:00
3   2022-06-19 00:15:00
4   2022-06-19 00:20:00
Name: datetime, dtype: datetime64[ns]

In [11]:
for df in [occ_df, vol_df, price_df, dur_df]:
    df['datetime'] = time_df['datetime'].values

print("✓ Datetime added to all tables")

✓ Datetime added to all tables

In [12]:
print("Melting occupancy... (this makes 2.1 million rows — that's correct!)")
occ_long = occ_df.melt(
    id_vars=['timestamp', 'datetime'],#keep them unchanged 
    var_name='station_id', # Bache hue columns hi heading
    value_name='occupancy'  #Bache hue columns ke Andar ka Data
)

print("Melting volume...")
vol_long = vol_df.melt(
    id_vars=['timestamp', 'datetime'],
    var_name='station_id',
    value_name='volume_kwh'
)

print("Melting price...")
price_long = price_df.melt(
    id_vars=['timestamp', 'datetime'],
    var_name='station_id',
    value_name='price_per_kwh'
)

print("Melting duration...")
dur_long = dur_df.melt(
    id_vars=['timestamp', 'datetime'],
    var_name='station_id',
    value_name='duration_hours'
)

print(f"\n✓ All tables melted. Long occupancy shape: {occ_long.shape}")

Melting occupancy... (this makes 2.1 million rows — that's correct!)
Melting volume...
Melting price...
Melting duration...

✓ All tables melted. Long occupancy shape: (2134080, 4)

In [13]:
occ_long.head(5)

   timestamp            datetime station_id  occupancy
0          1 2022-06-19 00:00:00        102         12
1          2 2022-06-19 00:05:00        102         12
2          3 2022-06-19 00:10:00        102         12
3          4 2022-06-19 00:15:00        102         12
4          5 2022-06-19 00:20:00        102         12

In [14]:
vol_long.head()

   timestamp            datetime station_id  volume_kwh
0          1 2022-06-19 00:00:00        102    2.858333
1          2 2022-06-19 00:05:00        102    4.375000
2          3 2022-06-19 00:10:00        102    4.375000
3          4 2022-06-19 00:15:00        102    4.375000
4          5 2022-06-19 00:20:00        102    4.375000

In [15]:
price_long.head()

   timestamp            datetime station_id  price_per_kwh
0          1 2022-06-19 00:00:00        102          0.924
1          2 2022-06-19 00:05:00        102          0.924
2          3 2022-06-19 00:10:00        102          0.924
3          4 2022-06-19 00:15:00        102          0.924
4          5 2022-06-19 00:20:00        102          0.924

In [16]:
dur_long.head()

   timestamp            datetime station_id  duration_hours
0          1 2022-06-19 00:00:00        102            0.49
1          2 2022-06-19 00:05:00        102            0.75
2          3 2022-06-19 00:10:00        102            0.75
3          4 2022-06-19 00:15:00        102            0.75
4          5 2022-06-19 00:20:00        102            0.75

In [17]:
#Like vlookup
master = occ_long.copy()
master = master.merge(vol_long[['timestamp','station_id','volume_kwh']],
                      on=['timestamp','station_id'])
master = master.merge(price_long[['timestamp','station_id','price_per_kwh']],
                      on=['timestamp','station_id'])
master = master.merge(dur_long[['timestamp','station_id','duration_hours']],
                      on=['timestamp','station_id'])

print(f"Master table shape: {master.shape}")
print(master.head().to_string(index=False))

Master table shape: (2134080, 7)
 timestamp            datetime station_id  occupancy  volume_kwh  price_per_kwh  duration_hours
         1 2022-06-19 00:00:00        102         12    2.858333          0.924            0.49
         2 2022-06-19 00:05:00        102         12    4.375000          0.924            0.75
         3 2022-06-19 00:10:00        102         12    4.375000          0.924            0.75
         4 2022-06-19 00:15:00        102         12    4.375000          0.924            0.75
         5 2022-06-19 00:20:00        102         12    4.375000          0.924            0.75

In [18]:
master['hour']       = master['datetime'].dt.hour
master['day_of_week'] = master['datetime'].dt.dayofweek  # 0=Monday, 6=Sunday
master['is_weekend'] = (master['day_of_week'] >= 5).astype(int)  # 1 if Sat/Sun
#convert to proper date time

In [19]:
def time_period(h):
    if 7 <= h < 12:  return 'Morning Peak'
    elif 12 <= h < 14: return 'Lunch'
    elif 14 <= h < 19: return 'Afternoon'
    elif 19 <= h < 23: return 'Evening'
    else:              return 'Night / Off-peak'

master['time_period'] = master['hour'].apply(time_period)

print("✓ Time features added: hour, day_of_week, is_weekend, time_period")

✓ Time features added: hour, day_of_week, is_weekend, time_period

In [20]:
print(master['time_period'].value_counts())

time_period
Night / Off-peak    711360
Morning Peak        444600
Afternoon           444600
Evening             355680
Lunch               177840
Name: count, dtype: int64

In [21]:
master['station_id'] = master['station_id'].astype(int)
info_df = info_df.rename(columns={'grid': 'station_id'})
master = master.merge(info_df[['station_id','count','fast_count','slow_count','CBD','area']],
                      on='station_id', how='left')
print(master.head())

   timestamp            datetime  station_id  occupancy  volume_kwh  \
0          1 2022-06-19 00:00:00         102         12    2.858333
1          2 2022-06-19 00:05:00         102         12    4.375000
2          3 2022-06-19 00:10:00         102         12    4.375000
3          4 2022-06-19 00:15:00         102         12    4.375000
4          5 2022-06-19 00:20:00         102         12    4.375000

   price_per_kwh  duration_hours  hour  day_of_week  is_weekend  \
0          0.924            0.49     0            6           1
1          0.924            0.75     0            6           1
2          0.924            0.75     0            6           1
3          0.924            0.75     0            6           1
4          0.924            0.75     0            6           1

        time_period  count  fast_count  slow_count  CBD  area
0  Night / Off-peak     30           3          27    0  0.71
1  Night / Off-peak     30           3          27    0  0.71
2  Night / Off-peak     30           3          27    0  0.71
3  Night / Off-peak     30           3          27    0  0.71
4  Night / Off-peak     30           3          27    0  0.71

In [22]:
master['utilization_rate'] = (master['occupancy'] / master['count']).clip(0, 1)
print(master.head())
#Agar utilization_rate > 0.85 (85% full): Toh station par bheed hai, "Dynamic Tariff" (Price) ko badha do!
# Agar utilization_rate < 0.20 (20% full): Toh station khali pada hai, Price ko kam karke logo ko attract karo!

   timestamp            datetime  station_id  occupancy  volume_kwh  \
0          1 2022-06-19 00:00:00         102         12    2.858333
1          2 2022-06-19 00:05:00         102         12    4.375000
2          3 2022-06-19 00:10:00         102         12    4.375000
3          4 2022-06-19 00:15:00         102         12    4.375000
4          5 2022-06-19 00:20:00         102         12    4.375000

   price_per_kwh  duration_hours  hour  day_of_week  is_weekend  \
0          0.924            0.49     0            6           1
1          0.924            0.75     0            6           1
2          0.924            0.75     0            6           1
3          0.924            0.75     0            6           1
4          0.924            0.75     0            6           1

        time_period  count  fast_count  slow_count  CBD  area  \
0  Night / Off-peak     30           3          27    0  0.71
1  Night / Off-peak     30           3          27    0  0.71
2  Night / Off-peak     30           3          27    0  0.71
3  Night / Off-peak     30           3          27    0  0.71
4  Night / Off-peak     30           3          27    0  0.71

   utilization_rate
0               0.4
1               0.4
2               0.4
3               0.4
4               0.4

In [23]:
master['revenue'] = master['volume_kwh'] * master['price_per_kwh']
print(master.head())

   timestamp            datetime  station_id  occupancy  volume_kwh  \
0          1 2022-06-19 00:00:00         102         12    2.858333
1          2 2022-06-19 00:05:00         102         12    4.375000
2          3 2022-06-19 00:10:00         102         12    4.375000
3          4 2022-06-19 00:15:00         102         12    4.375000
4          5 2022-06-19 00:20:00         102         12    4.375000

   price_per_kwh  duration_hours  hour  day_of_week  is_weekend  \
0          0.924            0.49     0            6           1
1          0.924            0.75     0            6           1
2          0.924            0.75     0            6           1
3          0.924            0.75     0            6           1
4          0.924            0.75     0            6           1

        time_period  count  fast_count  slow_count  CBD  area  \
0  Night / Off-peak     30           3          27    0  0.71
1  Night / Off-peak     30           3          27    0  0.71
2  Night / Off-peak     30           3          27    0  0.71
3  Night / Off-peak     30           3          27    0  0.71
4  Night / Off-peak     30           3          27    0  0.71

   utilization_rate  revenue
0               0.4   2.6411
1               0.4   4.0425
2               0.4   4.0425
3               0.4   4.0425
4               0.4   4.0425

# EDA begins

In [25]:
hourly = master.groupby('hour').agg(
    avg_occupancy    = ('occupancy', 'mean'),
    avg_utilization  = ('utilization_rate', 'mean'),
    avg_revenue      = ('revenue', 'mean')
).round(3)

print("\nHourly average stats (averaged across all 247 stations and 30 days):")
print(hourly.to_string())

Hourly average stats (averaged across all 247 stations and 30 days):
      avg_occupancy  avg_utilization  avg_revenue
hour
0            26.198            0.332       35.383
1            26.427            0.334       36.799
2            26.022            0.328       33.075
3            25.871            0.326       31.835
4            25.819            0.325       32.157
5            25.945            0.327       33.664
6            26.094            0.331       37.383
7            23.775            0.303       35.932
8            20.305            0.261       28.883
9            19.230            0.250       23.069
10           18.428            0.241       22.436
11           18.175            0.238       23.337
12           19.496            0.255       32.612
13           19.571            0.257       34.592
14           18.325            0.241       27.748
15           17.655            0.232       26.308
16           17.757            0.232       26.641
17           18.140            0.234       28.366
18           18.726            0.240       27.925
19           20.631            0.263       27.950
20           21.994            0.279       29.126
21           22.829            0.289       28.025
22           23.763            0.300       27.855
23           24.472            0.308       28.839